services:
  configsvr:
    image: mongo:6
    container_name: configsvr
    command: mongod --configsvr --replSet rs-config --port 27017 --bind_ip_all

  shard1:
    image: mongo:6
    container_name: shard1
    command: mongod --shardsvr --replSet rs-shard1 --port 27017 --bind_ip_all

  mongos:
    image: mongo:6
    container_name: mongos
    command: mongos --configdb rs-config/configsvr:27017 --port 27017 --bind_ip_all
    ports:
      - "27017:27017"
    depends_on:
      - configsvr
      - shard1

  api:
    build: .
    container_name: newsflow_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mongodb://mongos:27017
    depends_on:
      - mongos