services:
  configsvr:
    image: mongo:6
    container_name: configsvr
    command: mongod --configsvr --replSet rs-config --port 27017 --bind_ip_all
    networks:
      - newsflow_net

  shard1:
    image: mongo:6
    container_name: shard1
    command: mongod --shardsvr --replSet rs-shard1 --port 27017 --bind_ip_all
    networks:
      - newsflow_net

  shard2:
    image: mongo:6
    container_name: shard2
    command: mongod --shardsvr --replSet rs-shard2 --port 27017 --bind_ip_all
    networks:
      - newsflow_net

  mongos:
    image: mongo:6
    container_name: mongos
    command: mongos --configdb rs-config/configsvr:27017 --port 27017 --bind_ip_all
    ports:
      - "27017:27017"
    depends_on:
      - configsvr
      - shard1
      - shard2
    networks:
      - newsflow_net

  api:
    build: .
    container_name: newsflow_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - MONGODB_URL=mongodb://mongos:27017
    depends_on:
      - mongos
    networks:
      - newsflow_net

networks:
  newsflow_net:
    driver: bridge